resolver: lts-12.22
packages:
  - .
extra-deps:
# pinned versions of tools
  - ghcid-0.7.1
  - hindent-5.2.7
  - hlint-2.1.11
  - hoogle-5.0.17.3
  - stylish-haskell-0.9.2.0
  - weeder-1.0.8
  - present-4.1.0
  - hasktags-0.71.2
  - haskdogs-0.5.3
  - fast-tags-1.5.0
  - dhall-1.15.1
  - dhall-json-1.2.3
  - happy-1.19.9
  - alex-3.2.4
  - hpack-0.28.2
  - pandoc-2.2.1
  - summoner-1.0.6
  - cpphs-1.20.8
